// @generated by tools/gen-tables/gen.py from tools/gen-tables/gen.py. DO NOT EDIT.
//
// Regenerate with `make tables`; `make check` fails when this file drifts from
// the source (AD-14). The colours were transcribed from the Libre Edition
// *Master Tables* document, in which every cell carries its colour twice — as
// text and as cell shading — and the two encodings agree cell for cell
// (specs/README.md, provenance).

//! The generated ladder tables (AD-14).
//!
//! Nothing here is edited by hand. `tools/gen-tables/gen.py` reads
//! `specs/4c_system_master_tables.csv`, runs the authoritative property test
//! over it, and writes this module; `make check` fails when the two drift.

/// The Basic (13-row) ladder.
///
/// Generated from the authoritative CSV; the human-readable golden snapshot is
/// `tools/gen-tables/golden/basic.master-table.txt`.
pub mod basic;

use crate::l0::Ladder;
/// The ladder this build is compiled against.
///
/// The campaign fixes one ladder (02:02.2) and the choice is part of a save's
/// identity (02:02.9), so it is a compile-time constant rather than a runtime
/// option: a save created under one ladder must not be silently loaded under the
/// other.
pub static CAMPAIGN_LADDER: &Ladder = &basic::BASIC;
