#!/usr/bin/env python3
"""Generate the Rust Master Table from the authoritative CSV (AD-14).

The Master Table is not hand-typed data: it is a generated artifact, and the
generator refuses to emit anything the authoritative property test rejects
(05:05.2 step 1, 05:05.4).

    specs/4c_system_master_tables.csv   authoritative source
    specs/verify_master_tables.py       the property test (V1-V7)
            |
            v
    crates/kobra-core/src/tables/basic.rs        generated ladder  (one ladder, per M0)
    crates/kobra-core/src/tables/mod.rs          generated module root
    tools/gen-tables/golden/*.txt       golden snapshot, for a human diff

Why Python, and why it imports the verifier:

The property test already exists, in `specs/`, and is the thing the README calls
the runnable form of AD-14's tests 1-6. Re-implementing V1-V7 in Rust would give
two property tests that can disagree — exactly the failure AD-15 exists to
prevent for content, applied to the table. So the generator *is* a consumer of
that module: it loads the CSV through `verify_master_tables.load`, runs every
check, and only then emits. There is one implementation of the invariants.

M0 generates **one** ladder: the campaign picks a ladder and fixes it, and the
two are not nested, so a save's identity depends on the choice (02:02.2,
02:02.9). The generator is table-parameterised, so M1 adding `--ladder advanced`
is a flag and a constant, not a rewrite.

Usage:

    python3 tools/gen-tables/gen.py            # write the generated files
    python3 tools/gen-tables/gen.py --check    # report drift, write nothing
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

# Importing the verifier must not leave a `__pycache__` in `specs/`: the source
# tree is an input, and a generator that dirties its own inputs is a generator
# that makes `make check` fail for the wrong reason.
sys.dont_write_bytecode = True

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
SPECS = REPO_ROOT / "specs"
TABLES_DIR = REPO_ROOT / "crates" / "kobra-core" / "src" / "tables"
GOLDEN_DIR = HERE / "golden"

# The ladder this build compiles in. §02.2: the campaign picks one and fixes it.
DEFAULT_LADDER = "basic"

COLOUR_NAMES = {
    "Blck": "Colour::Blck",
    "Red": "Colour::Red",
    "Blue": "Colour::Blue",
    "Yel": "Colour::Yel",
}

# Compact letters for the golden snapshot, so a human can diff it against the
# tables printed in specs/README.md without counting columns.
GOLDEN_LETTERS = {"Blck": "K", "Red": "R", "Blue": "B", "Yel": "Y"}

HEADER = """\
// @generated by tools/gen-tables/gen.py from {source}. DO NOT EDIT.
//
// Regenerate with `make tables`; `make check` fails when this file drifts from
// the source (AD-14). The colours were transcribed from the Libre Edition
// *Master Tables* document, in which every cell carries its colour twice — as
// text and as cell shading — and the two encodings agree cell for cell
// (specs/README.md, provenance).

"""


def load_verifier():
    """Import `specs/verify_master_tables.py` as a module."""
    path = SPECS / "verify_master_tables.py"
    spec = importlib.util.spec_from_file_location("verify_master_tables", path)
    if spec is None or spec.loader is None:  # pragma: no cover - unreachable
        raise SystemExit(f"FAIL: {path} could not be imported")
    module = importlib.util.module_from_spec(spec)
    # Register before executing: the verifier uses `@dataclass`, which resolves
    # `cls.__module__` through `sys.modules` and fails on an unregistered module.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def emit_mod_rs() -> str:
    return HEADER.format(source="tools/gen-tables/gen.py") + """\
//! The generated ladder tables (AD-14).
//!
//! Nothing here is edited by hand. `tools/gen-tables/gen.py` reads
//! `specs/4c_system_master_tables.csv`, runs the authoritative property test
//! over it, and writes this module; `make check` fails when the two drift.

/// The Basic (13-row) ladder.
///
/// Generated from the authoritative CSV; the human-readable golden snapshot is
/// `tools/gen-tables/golden/basic.master-table.txt`.
pub mod basic;

use crate::l0::Ladder;
/// The ladder this build is compiled against.
///
/// The campaign fixes one ladder (02:02.2) and the choice is part of a save's
/// identity (02:02.9), so it is a compile-time constant rather than a runtime
/// option: a save created under one ladder must not be silently loaded under the
/// other.
pub static CAMPAIGN_LADDER: &Ladder = &basic::BASIC;
"""


def emit_basic_rs(table, ladder: str) -> str:
    buckets = table.buckets
    bands = table.ascending  # ascending Rank Value, which is how the ladder reads

    out = [HEADER.format(source="specs/4c_system_master_tables.csv")]
    out.append(
        "use crate::l0::{Band, Bucket, Colour, Ladder, Ruleset};\n\n"
    )

    out.append(
        "/// The `d%` buckets, ascending, tiling `0..=99` exactly.\n"
        "///\n"
        "/// The irregular `90-93 / 94-96 / 97-98 / 99` tail is intentional finer\n"
        "/// granularity at the top, not a hole to be \"fixed\" (02:02.2).\n"
        f"pub static BUCKETS: [Bucket; {len(buckets)}] = [\n"
    )
    for label in buckets:
        lo, hi = parse_bucket(label)
        out.append(f"    Bucket {{ lo: {lo}, hi: {hi} }},\n")
    out.append("];\n\n")

    out.append(
        "/// The rank bands, ascending by Rank Value. Index 0 is rank 0.\n"
        "///\n"
        "/// A band's `hi` is `i32::MAX` when the ladder's top band is open-ended;\n"
        "/// Basic's is not (its top row is exactly `1000`), so every bound here is\n"
        "/// a real Rank Value and everything above the last band clamps to it.\n"
        f"static BANDS: [Band; {len(bands)}] = [\n"
    )
    for label in bands:
        lo, hi = parse_band(label)
        hi_rust = "i32::MAX" if hi is None else str(hi)
        colours = table.colours(label)
        out.append(f"    Band {{\n        lo: {lo},\n        hi: {hi_rust},\n        colours: &[\n")
        for colour in colours:
            out.append(f"            {COLOUR_NAMES[colour]},\n")
        out.append("        ],\n    },\n")
    out.append("];\n\n")

    out.append(
        f"/// The {ladder.capitalize()} Master Table: "
        f"{len(bands)} rank bands × {len(buckets)} `d%` buckets.\n"
        "///\n"
        "/// `00-04` is Black in every row: the irreducible 5% failure band, and the\n"
        "/// cell the as-exported CSV quietly removed (specs/README.md).\n"
        f"pub static {ladder.upper()}: Ladder = Ladder {{\n"
        f"    ruleset: Ruleset::{ladder.capitalize()},\n"
        f'    name: "{ladder}",\n'
        "    buckets: &BUCKETS,\n"
        "    bands: &BANDS,\n"
        "};\n"
    )
    return "".join(out)


def emit_golden(table, ladder: str) -> str:
    """The compact K/R/B/Y grid, in the layout specs/README.md prints."""
    buckets = table.buckets
    bands = table.ascending
    band_width = max(len(b) for b in bands)
    lines = [
        f"# {ladder} Master Table — golden snapshot (AD-14, property test 7)",
        "#",
        "# Generated by tools/gen-tables/gen.py. A human diff of this file is what",
        "# establishes correctness; the property tests are a regression guard only",
        "# (specs/README.md). K=Blck R=Red B=Blue Y=Yel.",
        "#",
        "# buckets: " + " ".join(buckets),
        "",
    ]
    for label in reversed(bands):  # descending, as the source prints it
        row = "".join(GOLDEN_LETTERS[c] for c in table.colours(label))
        lines.append(f"{label.ljust(band_width)}  {row}")
    lines.append("")
    return "\n".join(lines)


def parse_band(label: str) -> tuple[int, int | None]:
    """"1000" -> (1000, 1000); "150-999" -> (150, 999); "5000+" -> (5000, None)."""
    if label.endswith("+"):
        return int(label[:-1]), None
    if "-" in label:
        lo, hi = label.split("-", 1)
        return int(lo), int(hi)
    return int(label), int(label)


def parse_bucket(label: str) -> tuple[int, int]:
    """"00-04" -> (0, 4); "99" -> (99, 99)."""
    if "-" in label:
        lo, hi = label.split("-", 1)
        return int(lo), int(hi)
    return int(label), int(label)


def build(ladder: str) -> dict[Path, str]:
    verifier = load_verifier()
    csv_path = SPECS / "4c_system_master_tables.csv"
    try:
        tables = verifier.load(csv_path)
        # Every invariant, over every table in the file. Both ladders are
        # validated; one is emitted.
        for name, check in verifier.CHECKS:
            check(tables)
    except verifier.Failure as exc:
        raise SystemExit(f"FAIL: the authoritative table is invalid: {exc}") from exc

    key = ladder.capitalize()
    if key not in tables:
        known = ", ".join(sorted(tables))
        raise SystemExit(f"FAIL: unknown ladder {ladder!r} (known: {known})")
    table = tables[key]

    return {
        TABLES_DIR / "mod.rs": emit_mod_rs(),
        TABLES_DIR / f"{ladder}.rs": emit_basic_rs(table, ladder),
        GOLDEN_DIR / f"{ladder}.master-table.txt": emit_golden(table, ladder),
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ladder", default=DEFAULT_LADDER, help="ladder to emit")
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift without writing (exit 1 on any difference)",
    )
    args = parser.parse_args(argv[1:])

    outputs = build(args.ladder)
    drift = []
    for path, content in outputs.items():
        existing = path.read_text() if path.is_file() else None
        if existing == content:
            continue
        if args.check:
            drift.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")

    if args.check:
        if drift:
            for path in drift:
                print(f"DRIFT: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print(
                "the generated tables are stale — run `make tables`",
                file=sys.stderr,
            )
            return 1
        print(f"tables: {args.ladder} is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
